version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.21
    ports:
      - 9217:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elastic_vol:/usr/share/elasticsearch/data
volumes:
  elastic_vol:
